# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GrainAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(641, 409))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.f_selected = QtWidgets.QFrame(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_selected.sizePolicy().hasHeightForWidth())
        self.f_selected.setSizePolicy(sizePolicy)
        self.f_selected.setMinimumSize(QtCore.QSize(300, 0))
        self.f_selected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_selected.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_selected.setObjectName("f_selected")
        self.gridLayout_17.addWidget(self.f_selected, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.gridLayout_17.addWidget(self.label_37, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.gridLayout_17.addWidget(self.label_35, 0, 0, 1, 1)
        self.gv_original = QtWidgets.QGraphicsView(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_original.sizePolicy().hasHeightForWidth())
        self.gv_original.setSizePolicy(sizePolicy)
        self.gv_original.setMinimumSize(QtCore.QSize(300, 0))
        self.gv_original.setObjectName("gv_original")
        self.gridLayout_17.addWidget(self.gv_original, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.f_proj_x = QtWidgets.QFrame(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_proj_x.sizePolicy().hasHeightForWidth())
        self.f_proj_x.setSizePolicy(sizePolicy)
        self.f_proj_x.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_proj_x.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_proj_x.setObjectName("f_proj_x")
        self.gridLayout_19.addWidget(self.f_proj_x, 1, 1, 1, 1)
        self.f_proj_y = QtWidgets.QFrame(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_proj_y.sizePolicy().hasHeightForWidth())
        self.f_proj_y.setSizePolicy(sizePolicy)
        self.f_proj_y.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_proj_y.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_proj_y.setObjectName("f_proj_y")
        self.gridLayout_19.addWidget(self.f_proj_y, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName("label_42")
        self.gridLayout_19.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.gridLayout_19.addWidget(self.label_45, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.f_x_sample = QtWidgets.QFrame(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_x_sample.sizePolicy().hasHeightForWidth())
        self.f_x_sample.setSizePolicy(sizePolicy)
        self.f_x_sample.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_x_sample.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_x_sample.setObjectName("f_x_sample")
        self.gridLayout_18.addWidget(self.f_x_sample, 2, 2, 1, 1)
        self.f_y_sample = QtWidgets.QFrame(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_y_sample.sizePolicy().hasHeightForWidth())
        self.f_y_sample.setSizePolicy(sizePolicy)
        self.f_y_sample.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_y_sample.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_y_sample.setObjectName("f_y_sample")
        self.gridLayout_18.addWidget(self.f_y_sample, 0, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.gridLayout_18.addWidget(self.label_41, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.gridLayout_18.addWidget(self.label_40, 2, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_44 = QtWidgets.QLabel(self.tab_8)
        self.label_44.setObjectName("label_44")
        self.gridLayout_16.addWidget(self.label_44, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_8)
        self.label_43.setObjectName("label_43")
        self.gridLayout_16.addWidget(self.label_43, 0, 0, 1, 1)
        self.f_r_comp = QtWidgets.QFrame(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_r_comp.sizePolicy().hasHeightForWidth())
        self.f_r_comp.setSizePolicy(sizePolicy)
        self.f_r_comp.setAutoFillBackground(True)
        self.f_r_comp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_r_comp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_r_comp.setObjectName("f_r_comp")
        self.gridLayout_16.addWidget(self.f_r_comp, 1, 1, 1, 1)
        self.f_r_recon = QtWidgets.QFrame(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_r_recon.sizePolicy().hasHeightForWidth())
        self.f_r_recon.setSizePolicy(sizePolicy)
        self.f_r_recon.setAutoFillBackground(True)
        self.f_r_recon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_r_recon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_r_recon.setObjectName("f_r_recon")
        self.gridLayout_16.addWidget(self.f_r_recon, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_13.addWidget(self.tabWidget_2, 1, 1, 3, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.cb_BGC_sample = QtWidgets.QComboBox(self.frame_3)
        self.cb_BGC_sample.setObjectName("cb_BGC_sample")
        self.cb_BGC_sample.addItem("")
        self.cb_BGC_sample.addItem("")
        self.gridLayout_14.addWidget(self.cb_BGC_sample, 3, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_14.addWidget(self.label_39, 2, 1, 1, 1)
        self.sb_snum_sample = QtWidgets.QSpinBox(self.frame_3)
        self.sb_snum_sample.setEnabled(False)
        self.sb_snum_sample.setObjectName("sb_snum_sample")
        self.gridLayout_14.addWidget(self.sb_snum_sample, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.gridLayout_14.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.gridLayout_14.addWidget(self.label_33, 0, 0, 1, 1)
        self.button_sample = QtWidgets.QPushButton(self.frame_3)
        self.button_sample.setObjectName("button_sample")
        self.gridLayout_14.addWidget(self.button_sample, 1, 0, 1, 1)
        self.sb_mh_sample = QtWidgets.QSpinBox(self.frame_3)
        self.sb_mh_sample.setMinimum(1)
        self.sb_mh_sample.setMaximum(300)
        self.sb_mh_sample.setProperty("value", 30)
        self.sb_mh_sample.setObjectName("sb_mh_sample")
        self.gridLayout_14.addWidget(self.sb_mh_sample, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_14.addWidget(self.label_38, 0, 1, 1, 1)
        self.button_startsample = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_startsample.sizePolicy().hasHeightForWidth())
        self.button_startsample.setSizePolicy(sizePolicy)
        self.button_startsample.setIconSize(QtCore.QSize(19, 19))
        self.button_startsample.setObjectName("button_startsample")
        self.gridLayout_14.addWidget(self.button_startsample, 0, 2, 3, 1)
        self.button_save_sample = QtWidgets.QPushButton(self.frame_3)
        self.button_save_sample.setObjectName("button_save_sample")
        self.gridLayout_14.addWidget(self.button_save_sample, 3, 2, 1, 1)
        self.gridLayout_13.addWidget(self.frame_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_FPS = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_FPS.sizePolicy().hasHeightForWidth())
        self.button_FPS.setSizePolicy(sizePolicy)
        self.button_FPS.setObjectName("button_FPS")
        self.gridLayout_4.addWidget(self.button_FPS, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 2, 0, 1, 1)
        self.logbox = QtWidgets.QTextEdit(self.frame)
        self.logbox.setObjectName("logbox")
        self.gridLayout_4.addWidget(self.logbox, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame, 0, 2, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(200, 371))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollArea_2.setLineWidth(1)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 300, 696))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scale_menu = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.scale_menu.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_menu.sizePolicy().hasHeightForWidth())
        self.scale_menu.setSizePolicy(sizePolicy)
        self.scale_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scale_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scale_menu.setObjectName("scale_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scale_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.scale_menu)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scale_menu)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.textBox_scaleU = QtWidgets.QLineEdit(self.scale_menu)
        self.textBox_scaleU.setObjectName("textBox_scaleU")
        self.gridLayout_3.addWidget(self.textBox_scaleU, 0, 1, 1, 1)
        self.spb_scaleSize = QtWidgets.QDoubleSpinBox(self.scale_menu)
        self.spb_scaleSize.setMaximum(99999.0)
        self.spb_scaleSize.setSingleStep(0.1)
        self.spb_scaleSize.setProperty("value", 1.0)
        self.spb_scaleSize.setObjectName("spb_scaleSize")
        self.gridLayout_3.addWidget(self.spb_scaleSize, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scale_menu)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.cmb_scalePos = QtWidgets.QComboBox(self.scale_menu)
        self.cmb_scalePos.setObjectName("cmb_scalePos")
        self.cmb_scalePos.addItem("")
        self.cmb_scalePos.addItem("")
        self.cmb_scalePos.addItem("")
        self.cmb_scalePos.addItem("")
        self.gridLayout_3.addWidget(self.cmb_scalePos, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.scale_menu, 26, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 20, 0, 1, 1)
        self.label_save = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_save.sizePolicy().hasHeightForWidth())
        self.label_save.setSizePolicy(sizePolicy)
        self.label_save.setObjectName("label_save")
        self.gridLayout_2.addWidget(self.label_save, 15, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 8, 0, 1, 3)
        self.button_save = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.button_save.setObjectName("button_save")
        self.gridLayout_2.addWidget(self.button_save, 16, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 3)
        self.line_folda = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.line_folda.setReadOnly(False)
        self.line_folda.setObjectName("line_folda")
        self.gridLayout_2.addWidget(self.line_folda, 12, 0, 1, 2)
        self.line_save = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.line_save.setReadOnly(False)
        self.line_save.setObjectName("line_save")
        self.gridLayout_2.addWidget(self.line_save, 16, 0, 1, 2)
        self.button_folda = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.button_folda.setObjectName("button_folda")
        self.gridLayout_2.addWidget(self.button_folda, 12, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 18, 0, 1, 3)
        self.cb_saveAll = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.cb_saveAll.setObjectName("cb_saveAll")
        self.gridLayout_2.addWidget(self.cb_saveAll, 17, 0, 1, 3)
        self.rb_filename = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.rb_filename.setObjectName("rb_filename")
        self.gridLayout_2.addWidget(self.rb_filename, 7, 0, 1, 3)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 4, 0, 1, 3)
        self.rb_subfolda = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.rb_subfolda.setChecked(True)
        self.rb_subfolda.setObjectName("rb_subfolda")
        self.gridLayout_2.addWidget(self.rb_subfolda, 6, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 23, 0, 1, 2)
        self.line_header = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.line_header.setObjectName("line_header")
        self.gridLayout_2.addWidget(self.line_header, 14, 0, 1, 2)
        self.label_folda = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_folda.sizePolicy().hasHeightForWidth())
        self.label_folda.setSizePolicy(sizePolicy)
        self.label_folda.setObjectName("label_folda")
        self.gridLayout_2.addWidget(self.label_folda, 10, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 13, 0, 1, 3)
        self.button_header = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.button_header.setObjectName("button_header")
        self.gridLayout_2.addWidget(self.button_header, 14, 2, 1, 1)
        self.cmb_format = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmb_format.setObjectName("cmb_format")
        self.cmb_format.addItem("")
        self.cmb_format.addItem("")
        self.cmb_format.addItem("")
        self.cmb_format.addItem("")
        self.gridLayout_2.addWidget(self.cmb_format, 3, 2, 1, 1)
        self.cmb_scaleType = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmb_scaleType.setObjectName("cmb_scaleType")
        self.cmb_scaleType.addItem("")
        self.cmb_scaleType.addItem("")
        self.cmb_scaleType.addItem("")
        self.cmb_scaleType.addItem("")
        self.gridLayout_2.addWidget(self.cmb_scaleType, 25, 1, 1, 2)
        self.spb_mpxa = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spb_mpxa.setMinimum(100)
        self.spb_mpxa.setMaximum(499999)
        self.spb_mpxa.setProperty("value", 200)
        self.spb_mpxa.setObjectName("spb_mpxa")
        self.gridLayout_2.addWidget(self.spb_mpxa, 23, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 25, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 19, 0, 1, 3)
        self.rb_none = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.rb_none.setChecked(False)
        self.rb_none.setObjectName("rb_none")
        self.gridLayout_2.addWidget(self.rb_none, 5, 0, 1, 3)
        self.spb_N = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spb_N.setMinimum(3)
        self.spb_N.setMaximum(200)
        self.spb_N.setProperty("value", 30)
        self.spb_N.setObjectName("spb_N")
        self.gridLayout_2.addWidget(self.spb_N, 20, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 24, 0, 1, 1)
        self.cmb_sampleType = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmb_sampleType.setObjectName("cmb_sampleType")
        self.cmb_sampleType.addItem("")
        self.cmb_sampleType.addItem("")
        self.gridLayout_2.addWidget(self.cmb_sampleType, 24, 2, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(240, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 815))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textbox_fpsPath = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.textbox_fpsPath.setObjectName("textbox_fpsPath")
        self.gridLayout_5.addWidget(self.textbox_fpsPath, 5, 0, 1, 3)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 12, 0, 1, 3)
        self.textbox_pcaSave = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.textbox_pcaSave.setObjectName("textbox_pcaSave")
        self.gridLayout_5.addWidget(self.textbox_pcaSave, 7, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.cmb_matrixPCA = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmb_matrixPCA.setObjectName("cmb_matrixPCA")
        self.cmb_matrixPCA.addItem("")
        self.cmb_matrixPCA.addItem("")
        self.gridLayout_5.addWidget(self.cmb_matrixPCA, 2, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 3)
        self.cmb_FPS = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmb_FPS.setObjectName("cmb_FPS")
        self.cmb_FPS.addItem("")
        self.cmb_FPS.addItem("")
        self.cmb_FPS.addItem("")
        self.gridLayout_5.addWidget(self.cmb_FPS, 1, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 6, 0, 1, 2)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_5.addWidget(self.line_8, 8, 0, 1, 3)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 3, 0, 1, 3)
        self.button_FPSpath = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_FPSpath.setObjectName("button_FPSpath")
        self.gridLayout_5.addWidget(self.button_FPSpath, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 4, 0, 1, 2)
        self.button_savePCApath = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_savePCApath.setObjectName("button_savePCApath")
        self.gridLayout_5.addWidget(self.button_savePCApath, 6, 2, 1, 1)
        self.frame_graph = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_graph.setEnabled(False)
        self.frame_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph.setObjectName("frame_graph")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_graph)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_28 = QtWidgets.QLabel(self.frame_graph)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 10, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_graph)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 15, 0, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.frame_graph)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 2)
        self.cmb_x = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_x.setObjectName("cmb_x")
        self.gridLayout_6.addWidget(self.cmb_x, 2, 1, 1, 1)
        self.dsb_markerSize = QtWidgets.QDoubleSpinBox(self.frame_graph)
        self.dsb_markerSize.setMinimum(0.1)
        self.dsb_markerSize.setMaximum(30.0)
        self.dsb_markerSize.setSingleStep(0.1)
        self.dsb_markerSize.setProperty("value", 5.0)
        self.dsb_markerSize.setObjectName("dsb_markerSize")
        self.gridLayout_6.addWidget(self.dsb_markerSize, 5, 1, 1, 1)
        self.cmb_sort = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_sort.setObjectName("cmb_sort")
        self.gridLayout_6.addWidget(self.cmb_sort, 9, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_graph)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 14, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_graph)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 8, 0, 1, 1)
        self.cmb_color = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_color.setObjectName("cmb_color")
        self.gridLayout_6.addWidget(self.cmb_color, 8, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_graph)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)
        self.cmb_y = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_y.setObjectName("cmb_y")
        self.gridLayout_6.addWidget(self.cmb_y, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_graph)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_graph)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 5, 0, 1, 1)
        self.cmb_plot = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_plot.setObjectName("cmb_plot")
        self.cmb_plot.addItem("")
        self.cmb_plot.addItem("")
        self.cmb_plot.addItem("")
        self.gridLayout_6.addWidget(self.cmb_plot, 1, 1, 1, 1)
        self.cmb_subsubcolor = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_subsubcolor.setObjectName("cmb_subsubcolor")
        self.gridLayout_6.addWidget(self.cmb_subsubcolor, 12, 1, 1, 1)
        self.cmb_subcolor = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_subcolor.setObjectName("cmb_subcolor")
        self.gridLayout_6.addWidget(self.cmb_subcolor, 10, 1, 1, 1)
        self.cmb_subsort = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_subsort.setObjectName("cmb_subsort")
        self.gridLayout_6.addWidget(self.cmb_subsort, 11, 1, 1, 1)
        self.cmb_subsubsort = QtWidgets.QComboBox(self.frame_graph)
        self.cmb_subsubsort.setObjectName("cmb_subsubsort")
        self.gridLayout_6.addWidget(self.cmb_subsubsort, 13, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_graph)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 12, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_graph)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 4, 0, 1, 1)
        self.spb_bins = QtWidgets.QSpinBox(self.frame_graph)
        self.spb_bins.setMinimum(1)
        self.spb_bins.setMaximum(200)
        self.spb_bins.setProperty("value", 10)
        self.spb_bins.setObjectName("spb_bins")
        self.gridLayout_6.addWidget(self.spb_bins, 6, 1, 1, 1)
        self.label_bins = QtWidgets.QLabel(self.frame_graph)
        self.label_bins.setObjectName("label_bins")
        self.gridLayout_6.addWidget(self.label_bins, 6, 0, 1, 1)
        self.dsb_alpha = QtWidgets.QDoubleSpinBox(self.frame_graph)
        self.dsb_alpha.setDecimals(1)
        self.dsb_alpha.setMinimum(0.1)
        self.dsb_alpha.setMaximum(1.0)
        self.dsb_alpha.setSingleStep(0.1)
        self.dsb_alpha.setProperty("value", 1.0)
        self.dsb_alpha.setObjectName("dsb_alpha")
        self.gridLayout_6.addWidget(self.dsb_alpha, 7, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_graph)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 7, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_graph, 13, 0, 1, 3)
        self.button_PCA = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.button_PCA.setObjectName("button_PCA")
        self.gridLayout_5.addWidget(self.button_PCA, 9, 0, 1, 3)
        self.label_14.raise_()
        self.line_7.raise_()
        self.label_12.raise_()
        self.button_FPSpath.raise_()
        self.textbox_fpsPath.raise_()
        self.label_13.raise_()
        self.button_savePCApath.raise_()
        self.textbox_pcaSave.raise_()
        self.line_8.raise_()
        self.line_4.raise_()
        self.frame_graph.raise_()
        self.cmb_FPS.raise_()
        self.label_11.raise_()
        self.cmb_matrixPCA.raise_()
        self.button_PCA.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.tab_pca = QtWidgets.QTabWidget(self.tab_2)
        self.tab_pca.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_pca.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_pca.setObjectName("tab_pca")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.logbox_pca = QtWidgets.QTextEdit(self.tab_4)
        self.logbox_pca.setObjectName("logbox_pca")
        self.gridLayout_12.addWidget(self.logbox_pca, 0, 0, 1, 1)
        self.tab_pca.addTab(self.tab_4, "")
        self.tn_summary = QtWidgets.QWidget()
        self.tn_summary.setObjectName("tn_summary")
        self.gridLayout = QtWidgets.QGridLayout(self.tn_summary)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.tn_summary)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.table_summary = QtWidgets.QTableView(self.tn_summary)
        self.table_summary.setObjectName("table_summary")
        self.gridLayout.addWidget(self.table_summary, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tn_summary)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 1)
        self.table_vector = QtWidgets.QTableView(self.tn_summary)
        self.table_vector.setObjectName("table_vector")
        self.gridLayout.addWidget(self.table_vector, 3, 0, 1, 1)
        self.tab_pca.addTab(self.tn_summary, "")
        self.tn_graph = QtWidgets.QWidget()
        self.tn_graph.setObjectName("tn_graph")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tn_graph)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.canvas = QtWidgets.QScrollArea(self.tn_graph)
        self.canvas.setWidgetResizable(True)
        self.canvas.setObjectName("canvas")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.canvas.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.addWidget(self.canvas, 0, 0, 1, 1)
        self.tab_pca.addTab(self.tn_graph, "")
        self.horizontalLayout.addWidget(self.tab_pca)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_9 = QtWidgets.QFrame(self.tab_3)
        self.frame_9.setMaximumSize(QtCore.QSize(150, 70))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_36 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_15.addWidget(self.label_36, 0, 0, 1, 1)
        self.cmb_recType = QtWidgets.QComboBox(self.frame_9)
        self.cmb_recType.setObjectName("cmb_recType")
        self.cmb_recType.addItem("")
        self.cmb_recType.addItem("")
        self.gridLayout_15.addWidget(self.cmb_recType, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_9, 0, 0, 1, 1)
        self.fg_1_1 = QtWidgets.QFrame(self.tab_3)
        self.fg_1_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fg_1_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fg_1_1.setObjectName("fg_1_1")
        self.gridLayout_10.addWidget(self.fg_1_1, 0, 1, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.button_saveReconst = QtWidgets.QPushButton(self.frame_2)
        self.button_saveReconst.setObjectName("button_saveReconst")
        self.gridLayout_8.addWidget(self.button_saveReconst, 10, 0, 1, 2)
        self.cmb_IIIP = QtWidgets.QComboBox(self.frame_2)
        self.cmb_IIIP.setEnabled(False)
        self.cmb_IIIP.setObjectName("cmb_IIIP")
        self.gridLayout_8.addWidget(self.cmb_IIIP, 6, 0, 1, 1)
        self.dsb_IIId = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_IIId.setEnabled(False)
        self.dsb_IIId.setDecimals(1)
        self.dsb_IIId.setMinimum(-5.0)
        self.dsb_IIId.setMaximum(5.0)
        self.dsb_IIId.setSingleStep(0.1)
        self.dsb_IIId.setObjectName("dsb_IIId")
        self.gridLayout_8.addWidget(self.dsb_IIId, 6, 1, 1, 1)
        self.cmb_sumDev = QtWidgets.QComboBox(self.frame_2)
        self.cmb_sumDev.setObjectName("cmb_sumDev")
        self.cmb_sumDev.addItem("")
        self.cmb_sumDev.addItem("")
        self.cmb_sumDev.addItem("")
        self.cmb_sumDev.addItem("")
        self.cmb_sumDev.addItem("")
        self.cmb_sumDev.addItem("")
        self.gridLayout_8.addWidget(self.cmb_sumDev, 1, 0, 1, 2)
        self.button_generate = QtWidgets.QPushButton(self.frame_2)
        self.button_generate.setObjectName("button_generate")
        self.gridLayout_8.addWidget(self.button_generate, 9, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 3, 1, 1, 1)
        self.dsb_Id = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_Id.setEnabled(False)
        self.dsb_Id.setDecimals(1)
        self.dsb_Id.setMinimum(-5.0)
        self.dsb_Id.setMaximum(5.0)
        self.dsb_Id.setSingleStep(0.1)
        self.dsb_Id.setObjectName("dsb_Id")
        self.gridLayout_8.addWidget(self.dsb_Id, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 2, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 2)
        self.dsb_IId = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dsb_IId.setEnabled(False)
        self.dsb_IId.setDecimals(1)
        self.dsb_IId.setMinimum(-5.0)
        self.dsb_IId.setMaximum(5.0)
        self.dsb_IId.setSingleStep(0.1)
        self.dsb_IId.setObjectName("dsb_IId")
        self.gridLayout_8.addWidget(self.dsb_IId, 5, 1, 1, 1)
        self.cmb_IP = QtWidgets.QComboBox(self.frame_2)
        self.cmb_IP.setEnabled(False)
        self.cmb_IP.setObjectName("cmb_IP")
        self.gridLayout_8.addWidget(self.cmb_IP, 4, 0, 1, 1)
        self.cmb_IIP = QtWidgets.QComboBox(self.frame_2)
        self.cmb_IIP.setEnabled(False)
        self.cmb_IIP.setObjectName("cmb_IIP")
        self.gridLayout_8.addWidget(self.cmb_IIP, 5, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.frame_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_8.addWidget(self.line_6, 7, 0, 1, 2)
        self.gridLayout_10.addWidget(self.frame_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 22))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menutest.addAction(self.actionAbout)
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.tab_pca.setCurrentIndex(0)
        self.cmb_format.currentIndexChanged['QString'].connect(MainWindow.setFormat)
        self.button_folda.clicked.connect(MainWindow.setFoldaPath)
        self.button_save.clicked.connect(MainWindow.setSavePath)
        self.cmb_sampleType.currentIndexChanged['QString'].connect(MainWindow.setBGC)
        self.spb_N.valueChanged['int'].connect(MainWindow.setN)
        self.spb_mpxa.valueChanged['int'].connect(MainWindow.setMPA)
        self.button_FPS.clicked.connect(MainWindow.startEFA)
        self.cmb_scaleType.currentIndexChanged['int'].connect(MainWindow.setScaleType)
        self.textBox_scaleU.textEdited['QString'].connect(MainWindow.setScaleUnit)
        self.spb_scaleSize.valueChanged['double'].connect(MainWindow.setScaleValue)
        self.cmb_scalePos.currentIndexChanged['int'].connect(MainWindow.setScalePosition)
        self.button_header.clicked.connect(MainWindow.setHeaderName)
        self.button_FPSpath.clicked.connect(MainWindow.setFPSPath)
        self.button_savePCApath.clicked.connect(MainWindow.setSavePCAPath)
        self.cmb_matrixPCA.currentIndexChanged['int'].connect(MainWindow.setPCAmatrix)
        self.button_PCA.clicked.connect(MainWindow.startPCA)
        self.cmb_x.currentIndexChanged['int'].connect(MainWindow.setXaxis)
        self.cmb_y.currentIndexChanged['int'].connect(MainWindow.setYaxis)
        self.cmb_color.currentIndexChanged['int'].connect(MainWindow.setColor)
        self.pushButton.clicked.connect(MainWindow.graphDraw)
        self.pushButton_2.clicked.connect(MainWindow.savePCFig)
        self.cmb_sort.currentIndexChanged['int'].connect(MainWindow.setSort)
        self.cmb_plot.currentIndexChanged['int'].connect(MainWindow.setPlotType)
        self.cmb_recType.currentIndexChanged['int'].connect(MainWindow.setReconstMode)
        self.cmb_sumDev.currentIndexChanged['int'].connect(MainWindow.setSumDev)
        self.cmb_IP.currentIndexChanged['int'].connect(MainWindow.setIPCaxis)
        self.cmb_IIP.currentIndexChanged['int'].connect(MainWindow.setIIPCaxis)
        self.cmb_IIIP.currentIndexChanged['int'].connect(MainWindow.setIIIPCaxis)
        self.dsb_Id.valueChanged['double'].connect(MainWindow.setIdev)
        self.dsb_IId.valueChanged['double'].connect(MainWindow.setIIdev)
        self.dsb_IIId.valueChanged['double'].connect(MainWindow.setIIIdev)
        self.button_generate.clicked.connect(MainWindow.reconstGraph)
        self.button_saveReconst.clicked.connect(MainWindow.saveReconstGraph)
        self.cmb_FPS.currentIndexChanged['int'].connect(MainWindow.setFPSorEFD)
        self.cmb_subcolor.currentIndexChanged['int'].connect(MainWindow.setSubColor)
        self.cmb_subsort.currentIndexChanged['int'].connect(MainWindow.setSubSort)
        self.cmb_subsubcolor.currentIndexChanged['int'].connect(MainWindow.setSubsubColor)
        self.cmb_subsubsort.currentIndexChanged['int'].connect(MainWindow.setSubsubSort)
        self.rb_none.toggled['bool'].connect(MainWindow.setCategorize)
        self.rb_subfolda.toggled['bool'].connect(MainWindow.setCategorize)
        self.rb_filename.toggled['bool'].connect(MainWindow.setCategorize)
        self.button_sample.clicked.connect(MainWindow.setSampleImage)
        self.button_startsample.clicked.connect(MainWindow.startPlayground)
        self.button_save_sample.clicked.connect(MainWindow.saveSample)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_37.setText(_translate("MainWindow", "Selected Sample"))
        self.label_35.setText(_translate("MainWindow", "Selected Image"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Original"))
        self.label_42.setText(_translate("MainWindow", "Y"))
        self.label_45.setText(_translate("MainWindow", "X"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "Projection"))
        self.label_41.setText(_translate("MainWindow", "Y Coordinate"))
        self.label_40.setText(_translate("MainWindow", "X Coordinate"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Fourier Approximation"))
        self.label_44.setText(_translate("MainWindow", "Comperison"))
        self.label_43.setText(_translate("MainWindow", "Reconstructed (EFA)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Reconstruct"))
        self.cb_BGC_sample.setItemText(0, _translate("MainWindow", "White"))
        self.cb_BGC_sample.setItemText(1, _translate("MainWindow", "Black"))
        self.label_39.setText(_translate("MainWindow", "Background Color of Image"))
        self.label_34.setText(_translate("MainWindow", "Select Sample number"))
        self.label_33.setText(_translate("MainWindow", "Select Image"))
        self.button_sample.setText(_translate("MainWindow", "Choose"))
        self.label_38.setText(_translate("MainWindow", "Maximum Harmonics Number"))
        self.button_startsample.setText(_translate("MainWindow", "Start!"))
        self.button_save_sample.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Playground"))
        self.button_FPS.setText(_translate("MainWindow", "Analyze"))
        self.logbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">Image Analysis</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">What you can do here is to extract parameters of Fourier series and other basic shape parameters from your dataset.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After the analysis, the results will be saved as &quot;<span style=\" color:#000000;\">FPS.csv</span>&quot;.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Principal Component Analysis</span> (<span style=\" color:#000000;\">PCA</span>) will be held at next tub and it is based on the output CSV file \'<span style=\" color:#000000;\">FPS.csv</span>\'.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Brief Usage</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Select your file format of image files.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Choose the method for categorization</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Select the folda in which all your image files contains</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. If you are going to categorize your data based on subfolda or filenames, assign each category class.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   <span style=\" font-weight:600;\">NOTE:</span> <span style=\" font-weight:600;\">you must devided each category name by using underbar \'_\'</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">For example, your folda directory is like</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Data --- TYPE_A -- No1 --- sample_001.png</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">          |                    - No2 --- sample_002.png</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">           -- TYPE_B -- No2 --- sample_003.png</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                               |           -- sample_004.png</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                - No3 --- sample_005.png</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">then, you should put, for instance, \'TYPE_Number_sample\' into the textbox of category class.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Then, the header row of exported csv file will be automatically assigned based on these category names.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5. Select the folda in which the resultant CSV file is to save.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6. Set the background color (if which is wrongly choosed, the data goes wrong).</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7. Select the Maximum Harmonics number.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  What is maximum harmonics number (<span style=\" font-style:italic;\">N</span>)? You can check how this number affects the results at &quot;Playground&quot; tab.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#fc0107;\">NOTE: Your sample size must be larger than at least 4*</span><span style=\" font-weight:600; font-style:italic; color:#fc0107;\">N</span><span style=\" font-weight:600; color:#fc0107;\">, otherwise you CANNOT conduct PCA at next tub.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8. Choose minimum pixel area of samples so that you can exclude noise from your data.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9. set Scale. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can choose 2D or 1D scale.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In the case of 2D scale, your data will be scaled based on the area of the scale object.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In the case of 1D scale, your data will be scaled based on the  length of the scale object.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10. Press &quot;Analyze&quot; button.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If your analysis ends, please go to the PCA tab.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#---------------------------------</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", " Log"))
        self.label_9.setText(_translate("MainWindow", "Scale Unit"))
        self.label_8.setText(_translate("MainWindow", "Scale Size"))
        self.label_10.setText(_translate("MainWindow", "Position"))
        self.cmb_scalePos.setItemText(0, _translate("MainWindow", "Top"))
        self.cmb_scalePos.setItemText(1, _translate("MainWindow", "Bottom"))
        self.cmb_scalePos.setItemText(2, _translate("MainWindow", "Right"))
        self.cmb_scalePos.setItemText(3, _translate("MainWindow", "Left"))
        self.label_4.setText(_translate("MainWindow", "Maximum Harmonics"))
        self.label_save.setText(_translate("MainWindow", "Save results to *"))
        self.label.setText(_translate("MainWindow", "Image format"))
        self.button_save.setText(_translate("MainWindow", "select"))
        self.label_3.setText(_translate("MainWindow", "Initial Setting of Fourier Analysis"))
        self.button_folda.setText(_translate("MainWindow", "Select"))
        self.label_31.setText(_translate("MainWindow", "NOTE: It might take long time"))
        self.cb_saveAll.setText(_translate("MainWindow", "Save all Normalized samples data"))
        self.rb_filename.setText(_translate("MainWindow", "file name (devide each category by \'_\')"))
        self.label_32.setText(_translate("MainWindow", "Categorize your files based on..."))
        self.rb_subfolda.setText(_translate("MainWindow", "name of subfolda"))
        self.label_5.setText(_translate("MainWindow", "minimum Pixel Area"))
        self.label_folda.setText(_translate("MainWindow", "Import images from *"))
        self.label_17.setText(_translate("MainWindow", "Category class name (not mandatory)"))
        self.button_header.setText(_translate("MainWindow", "assign"))
        self.cmb_format.setItemText(0, _translate("MainWindow", ".png"))
        self.cmb_format.setItemText(1, _translate("MainWindow", ".BMP"))
        self.cmb_format.setItemText(2, _translate("MainWindow", ".jpeg"))
        self.cmb_format.setItemText(3, _translate("MainWindow", ".jpg"))
        self.cmb_scaleType.setItemText(0, _translate("MainWindow", "No scale"))
        self.cmb_scaleType.setItemText(1, _translate("MainWindow", "2-D (Area)"))
        self.cmb_scaleType.setItemText(2, _translate("MainWindow", "1-D (X-Length)"))
        self.cmb_scaleType.setItemText(3, _translate("MainWindow", "1-D (Y-Length)"))
        self.label_7.setText(_translate("MainWindow", "Scale setting"))
        self.rb_none.setText(_translate("MainWindow", "None"))
        self.label_6.setText(_translate("MainWindow", "Background Color"))
        self.cmb_sampleType.setItemText(0, _translate("MainWindow", "White"))
        self.cmb_sampleType.setItemText(1, _translate("MainWindow", "Black"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Image Analysis"))
        self.label_11.setText(_translate("MainWindow", "Matrix"))
        self.cmb_matrixPCA.setItemText(0, _translate("MainWindow", "Correlation"))
        self.cmb_matrixPCA.setItemText(1, _translate("MainWindow", "Covariance"))
        self.label_14.setText(_translate("MainWindow", "Initial Setting of PCA"))
        self.cmb_FPS.setItemText(0, _translate("MainWindow", "FPS (Non-Directional)"))
        self.cmb_FPS.setItemText(1, _translate("MainWindow", "Amplitude of Harmonics"))
        self.cmb_FPS.setItemText(2, _translate("MainWindow", "EFD (Directional)"))
        self.label_13.setText(_translate("MainWindow", "Save Folda*"))
        self.button_FPSpath.setText(_translate("MainWindow", "Select"))
        self.label_12.setText(_translate("MainWindow", "File Folda*"))
        self.button_savePCApath.setText(_translate("MainWindow", "Select"))
        self.label_28.setText(_translate("MainWindow", "SubGroup"))
        self.pushButton_2.setText(_translate("MainWindow", "Save As..."))
        self.label_22.setText(_translate("MainWindow", "Graph Setting"))
        self.pushButton.setText(_translate("MainWindow", "Preview"))
        self.label_20.setText(_translate("MainWindow", "Category"))
        self.label_18.setText(_translate("MainWindow", "X-axis"))
        self.label_24.setText(_translate("MainWindow", "Plot"))
        self.label_21.setText(_translate("MainWindow", "Size"))
        self.cmb_plot.setItemText(0, _translate("MainWindow", "Scatter"))
        self.cmb_plot.setItemText(1, _translate("MainWindow", "Density"))
        self.cmb_plot.setItemText(2, _translate("MainWindow", "Histogram"))
        self.label_29.setText(_translate("MainWindow", "SubsubGroup"))
        self.label_19.setText(_translate("MainWindow", "Y-axis"))
        self.label_bins.setText(_translate("MainWindow", "bins"))
        self.label_30.setText(_translate("MainWindow", "alpha"))
        self.button_PCA.setText(_translate("MainWindow", "PCA"))
        self.logbox_pca.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">Principal Component Analysys (PCA)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can choose FPS or EFD for PCA both of which are exported as FPS.csv by the image analysis</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#fc000a;\">Note that you have to choose the folda which include FPS.csv as File Path otherwise you </span><span style=\" text-decoration: underline; color:#fc000a;\">cannot</span><span style=\" color:#fc000a;\"> do PCA.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">FPS.csv is the file which should be exported at image analysis Page.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline; color:#000000;\">1. Brief explanation of methodology</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">You can choose which parameter you use for the principal component analysis (PCA).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">There are three options: FPS, Amplitudes of Harmonics and traditional EFD.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Fist of all, the shape of samples were converted into the numerical dataset at &quot;Image Analysis&quot; sections as EFDs.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Each of your samples was decomposed into the harmonics ellipses of which total number is </span><span style=\" font-style:italic; color:#000000;\">N</span><span style=\" color:#000000;\"> (Maximum harmonics number).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Each harmonics ellipses can be described with four constant coefficients </span><span style=\" font-style:italic; color:#000000;\">a</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">, </span><span style=\" font-style:italic; color:#000000;\">b</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">, </span><span style=\" font-style:italic; color:#000000;\">c</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\"> and </span><span style=\" font-style:italic; color:#000000;\">d</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" font-style:italic; color:#000000;\"> </span><span style=\" color:#000000;\">where </span><span style=\" font-style:italic; color:#000000;\">n </span><span style=\" color:#000000;\">=</span><span style=\" font-style:italic; color:#000000;\">1,2,...N</span><span style=\" color:#000000;\">.  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">Thus each sample has </span><span style=\" font-style:italic; color:#000000;\">4*N</span><span style=\" color:#000000;\"> coefficients.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">EFD </span>(Elliptic Fourier Descriptor)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is traditional descriptor which corresponds to each coefficient of harmonics: <span style=\" font-style:italic; color:#000000;\">a</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">, </span><span style=\" font-style:italic; color:#000000;\">b</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">, </span><span style=\" font-style:italic; color:#000000;\">c</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\"> and </span><span style=\" font-style:italic; color:#000000;\">d</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">EFD-based PCA is suitble for directional data such as fossils and other organic matters (see Kuhl and Giardina 1982) .  HOWEVER, in the case of non-directional dataset such as grains, EFD-based PCA often do not work well. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is because EFD-based PCA often ends up  concluding that the shape variation is summarized by mirror symmetric properties which, in most cases, have no scientific interest of particle shapes.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">FPS</span> (Fourier Power Spectra)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It corresponds to thehalf of sum of squares of EFDs: FPS<span style=\" vertical-align:sub;\">n</span> = (<span style=\" font-style:italic; color:#000000;\">a</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">,^2 + </span><span style=\" font-style:italic; color:#000000;\">b</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">^2 + </span><span style=\" font-style:italic; color:#000000;\">c</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">^2 + </span><span style=\" font-style:italic; color:#000000;\">d</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">^2</span>)/2. This parameters no longer have the information of phase shift of each harmonics ellipses and solve the &quot;mirror-symmetric property&quot; problems.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Amplitude based</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It corresponds to the amplitude of the each harmonics in terms of X-coordinate and Y-coordinate respectively.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It is given by X<span style=\" vertical-align:sub;\">am</span> = (<span style=\" font-style:italic; color:#000000;\">a</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">,^2 + </span><span style=\" font-style:italic; color:#000000;\">b</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">^2) /2 , </span> Y<span style=\" vertical-align:sub;\">am</span> = (c<span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">,^2 + d</span><span style=\" font-style:italic; color:#000000; vertical-align:sub;\">n</span><span style=\" color:#000000;\">^2) /2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">This also solves </span>&quot;mirror-symmetric property&quot; problems.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">#---------------------------------</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tab_pca.setTabText(self.tab_pca.indexOf(self.tab_4), _translate("MainWindow", "Log"))
        self.label_15.setText(_translate("MainWindow", "PCA summary"))
        self.label_16.setText(_translate("MainWindow", "PCA eigen vector"))
        self.tab_pca.setTabText(self.tab_pca.indexOf(self.tn_summary), _translate("MainWindow", "Summary"))
        self.tab_pca.setTabText(self.tab_pca.indexOf(self.tn_graph), _translate("MainWindow", "Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PCA"))
        self.label_36.setText(_translate("MainWindow", "Shape Reconst."))
        self.cmb_recType.setItemText(0, _translate("MainWindow", "Summary"))
        self.cmb_recType.setItemText(1, _translate("MainWindow", "Detail"))
        self.button_saveReconst.setText(_translate("MainWindow", "Save Fig"))
        self.cmb_sumDev.setItemText(0, _translate("MainWindow", "±0.5 σ"))
        self.cmb_sumDev.setItemText(1, _translate("MainWindow", "±1.0 σ"))
        self.cmb_sumDev.setItemText(2, _translate("MainWindow", "±1.5 σ"))
        self.cmb_sumDev.setItemText(3, _translate("MainWindow", "±2.0 σ"))
        self.cmb_sumDev.setItemText(4, _translate("MainWindow", "±2.5 σ"))
        self.cmb_sumDev.setItemText(5, _translate("MainWindow", "±3.0 σ"))
        self.button_generate.setText(_translate("MainWindow", "Generate"))
        self.label_26.setText(_translate("MainWindow", " dev.(σ)"))
        self.label_27.setText(_translate("MainWindow", "Detail Mode"))
        self.label_25.setText(_translate("MainWindow", "PC"))
        self.label_23.setText(_translate("MainWindow", "Summary MODE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Shape"))
        self.menutest.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
